### PR TITLE
Optimize CGC computations

### PR DESCRIPTION
**Pull request by lkdvos**
This PR adds some optimizations for computing CGCs:

- Add a special case for dealing with Clebsch-Gordan coefficients when one of the sectors is trivial, i.e. $a \otimes I \rightarrow a$ or $I \otimes a \rightarrow a$. For these cases the CGCs are just the identity matrices, thus no computations are needed.
- Change the way `lower_weight_CGC!` works: solve equations using `qr!` instead of `pinv`, and build `rhs` differently.
- Purge values that are almost zero from the final result to save memory on disk and in RAM.

### CODE REVIEW

**Comment by lkdvos** [comment]
I've added some benchmarks for some improved version of the CGC computations, which now use QR instead of SVD to solve the linear problems, along with some in-place optimizations etc. I'll post the results here when they are done, and then check on how to add everything.

**Comment by lkdvos** [comment]
The results are in:
SUN_CGC_benchmarks
https://gist.github.com/lkdvos/4030a328fc12ea3c939d0b5ccec3ad4a

Looks like a serious upgrade, so I'll clean up this PR and implement everything nicely.

**Comment by Jutho** [comment]
Looking good. I am wondering which of the changes contributes most to the nice speedup. Threading over the fusion degeneracy `N123` is no longer possible with the storage recycling for building the right hand side, but I assume threading happens at the higher level anyway.

**Comment by lkdvos** [comment]
I actually think that using the threads for BLAS might actually be the best here, and even still, it would not be that hard to define the auxiliary vectors one loop lower, and re-use them only for the different m3s. In any case, the biggest speedup comes from the `qr!` and `ldiv!` from what I could find, and afterwards I changed how the arrays were built because of needing them in a dense format afterwards anyways.
I think it is probably harder to find the optimal threading strategy over a wide variety of cases/machines, so I would say that the current approach is quite nice.

**Pull request merged**
